// <auto-generated />
using System;
using HApi.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HApi.Migrations
{
    [DbContext(typeof(HContext))]
    [Migration("20210711065212_ConnectionTables")]
    partial class ConnectionTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("HApi.DataAccess.Entities.CPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MHZ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumCores")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("CPUs");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MotherboardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MotherboardId");

                    b.HasIndex("UserId");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.ComputerCPU", b =>
                {
                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CPUId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComputerId", "CPUId");

                    b.HasIndex("CPUId");

                    b.ToTable("ComputerCPU");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.ComputerGPU", b =>
                {
                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GPUId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComputerId", "GPUId");

                    b.HasIndex("GPUId");

                    b.ToTable("ComputerGPU");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.ComputerHDD", b =>
                {
                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HDDId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComputerId", "HDDId");

                    b.HasIndex("HDDId");

                    b.ToTable("ComputerHDD");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.ComputerNetworkCard", b =>
                {
                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetworkCardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComputerId", "NetworkCardId");

                    b.HasIndex("NetworkCardId");

                    b.ToTable("ComputerNetworkCard");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.ComputerRAM", b =>
                {
                    b.Property<int>("ComputerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RAMId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComputerId", "RAMId");

                    b.HasIndex("RAMId");

                    b.ToTable("ComputerRAM");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.Folder", b =>
                {
                    b.Property<int>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("FolderId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.GPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoreMhz")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemMhz")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumCores")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("GPUs");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.HDD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("HDDs");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.Motherboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CPUSlots")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PCISlots")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("RAMSlots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SataSlots")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Motherboards");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.NetworkCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kbs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("NetworkCards");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.Profile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.RAM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MHZ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("RAMs");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password_SHA256")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProfileUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("ProfileUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.Computer", b =>
                {
                    b.HasOne("HApi.DataAccess.Entities.Motherboard", "Motherboard")
                        .WithMany()
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HApi.DataAccess.Entities.User", null)
                        .WithMany("Computers")
                        .HasForeignKey("UserId");

                    b.Navigation("Motherboard");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.ComputerCPU", b =>
                {
                    b.HasOne("HApi.DataAccess.Entities.CPU", "CPU")
                        .WithMany()
                        .HasForeignKey("CPUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HApi.DataAccess.Entities.Computer", "Computer")
                        .WithMany("CPUs")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");

                    b.Navigation("CPU");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.ComputerGPU", b =>
                {
                    b.HasOne("HApi.DataAccess.Entities.Computer", "Computer")
                        .WithMany("GPUs")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HApi.DataAccess.Entities.GPU", "GPU")
                        .WithMany()
                        .HasForeignKey("GPUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");

                    b.Navigation("GPU");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.ComputerHDD", b =>
                {
                    b.HasOne("HApi.DataAccess.Entities.Computer", "Computer")
                        .WithMany("HDDs")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HApi.DataAccess.Entities.HDD", "HDD")
                        .WithMany()
                        .HasForeignKey("HDDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");

                    b.Navigation("HDD");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.ComputerNetworkCard", b =>
                {
                    b.HasOne("HApi.DataAccess.Entities.Computer", "Computer")
                        .WithMany("NetworkCards")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HApi.DataAccess.Entities.NetworkCard", "NetworkCard")
                        .WithMany()
                        .HasForeignKey("NetworkCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");

                    b.Navigation("NetworkCard");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.ComputerRAM", b =>
                {
                    b.HasOne("HApi.DataAccess.Entities.Computer", "Computer")
                        .WithMany("RAMs")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HApi.DataAccess.Entities.RAM", "RAM")
                        .WithMany()
                        .HasForeignKey("RAMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");

                    b.Navigation("RAM");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.User", b =>
                {
                    b.HasOne("HApi.DataAccess.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileUserId");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.Computer", b =>
                {
                    b.Navigation("CPUs");

                    b.Navigation("GPUs");

                    b.Navigation("HDDs");

                    b.Navigation("NetworkCards");

                    b.Navigation("RAMs");
                });

            modelBuilder.Entity("HApi.DataAccess.Entities.User", b =>
                {
                    b.Navigation("Computers");
                });
#pragma warning restore 612, 618
        }
    }
}
